import pathlib
import pandas as pd


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    """
    def __init__(self, data_fname: pathlib.Path):
        try:
            assert data_fname.exists()
        except AssertionError:
            raise ValueError(f"Filename {data_fname} doesn't exist.")
        except AttributeError:
            self.data_fname = pathlib.Path(data_fname)
        else:
            self.data_fname = data_fname

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the variable self.data.
        """
        data = pd.read_json(self.data_fname)
